fix steps of install scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,6 @@
 #!/bin/bash
 set -e
 
-# Initialize git submodules to retrieve scripts.
-git submodule update --init --recursive || { echo "Error initializing git submodules"; exit 1; }
-
-REPOS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
-SCRIPT_DIR="$REPOS_DIR/scripts"
-source "$SCRIPT_DIR/logs"
-source "$SCRIPT_DIR/utils"
-
 # Help option
 if [[ "$1" == "--help" ]]; then
     echo "Usage: install [--help]"
@@ -16,6 +8,12 @@ if [[ "$1" == "--help" ]]; then
     echo "It initializes git submodules, installs necessary tools, and sets up the environment."
     exit 0
 fi
+
+# Initialize git submodules to retrieve scripts.
+git submodule update --init --recursive nvim scripts || { echo "Error initializing git submodules"; exit 1; }
+
+DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
+SCRIPT_DIR="$DOTFILES_DIR/scripts"
 
 # Call the install script
 source "$SCRIPT_DIR/install"
diff --git a/setup_dotfiles b/setup_dotfiles
--- a/setup_dotfiles
+++ b/setup_dotfiles
@@ -1,11 +1,5 @@
 #!/bin/bash
 
-DOTFILES_DIR="$HOME/repos/dotfiles"
-SCRIPT_DIR="$DOTFILES_DIR/scripts"
-
-source "$SCRIPT_DIR/logs"
-source "$SCRIPT_DIR/utils"
-
 # Help option
 if [[ "$1" == "--help" ]]; then
     echo "Usage: setup_dotfiles [--help]"
@@ -14,9 +8,13 @@ if [[ "$1" == "--help" ]]; then
     exit 0
 fi
 
-# Install git submodules
-git submodule update --init --recursive || error_exit "Failed to install git submodules."
+# Initialize git submodules to retrieve scripts.
+git submodule update --init --recursive || { echo "Error initializing git submodules"; exit 1; }
 
+DOTFILES_DIR="$HOME/repos/dotfiles"
+SCRIPT_DIR="$DOTFILES_DIR/scripts"
+
+# Call the setup script
 source "$SCRIPT_DIR/setup"
 
 # Change the default shell to zsh
